#!/usr/bin/env zsh


OMZ_REP_URL="https://github.com/ohmyzsh/ohmyzsh.git"
OMZ_HOME_PATH="$HOME/.config/oh-my-zsh"



command_exists() {
    command -v $* >/dev/null
}

# Checking if git is installed
command_exists git || {
    printf "%s\n"   "git is not installed!"
    printf "%s\n\n" "Install git and try again..."
    exit 1
}


# Installing the oh-my-zsh framework
printf "%s " "Installing oh-my-zsh:" \
    && git clone $OMZ_REP_URL $OMZ_HOME_PATH &>/dev/null \
    && printf "%s\n" "OK!" \
    || {
    printf "%s\n"   "FAIL!"
    printf "%s\n\n" "Error while cloning repository."
    exit 1
}


# Installing the plugin zsh-autosuggestions
printf "%s " "Installing the plugin zsh-autosuggestions:" \
    && git clone https://github.com/zsh-users/zsh-autosuggestions \
        $OMZ_HOME_PATH/custom/plugins/zsh-autosuggestions &>/dev/null \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# Installing the plugin zsh-syntax-highlighting
printf "%s " "Installing the plugin zsh-syntax-highlighting:" \
    && git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
        $OMZ_HOME_PATH/custom/plugins/zsh-syntax-highlighting &>/dev/null \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# Installing the plugin zsh-history-substring-search
printf "%s " "Installing the plugin zsh-history-substring-search:" \
    && git clone https://github.com/zsh-users/zsh-history-substring-search \
        $OMZ_HOME_PATH/custom/plugins/zsh-history-substring-search &>/dev/null \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# ---- Installing symlinks ----

# alacritty
printf "%s " "Installing a symlink for alacritty:" \
    && ln -s ~/.dotfiles/.config/alacritty ~/.config/alacritty \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# bat
printf "%s " "Installing a symlink for bat: " \
    && ln -s ~/.dotfiles/.config/bat ~/.config/bat \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# starship
printf "%s " "Installing a symlink for starship: " \
    && ln -s ~/.dotfiles/.config/starship.toml ~/.config/starship.toml \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# tmux
printf "%s " "Installing a symlink for tmux: " \
    && ln -s ~/.dotfiles/.config/tmux ~/.config/tmux \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# nvim
printf "%s " "Installing a symlink for nvim: " \
    && mkdir ~/.config/nvim &>/dev/null \
    && ln -s ~/.dotfiles/.config/nvim/init.vim ~/.config/nvim/init.vim \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# neofetch
printf "%s " "Installing a symlink for neofetch:" \
    && ln -s ~/.dotfiles/.config/neofetch ~/.config/neofetch \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"

# zshrc
printf "%s " "Installing a symlink for zshrc: " \
    && mv ~/.zshrc ~/.zshrc.old \
    && ln -s ~/.dotfiles/.zshrc ~/.zshrc \
    && printf "%s\n" "OK!" || printf "%s\n" "FAIL!"


# ---- build cache ----
command_exists bat && bat cache --build &>/dev/null

